-- Kindr Seed Data - USA Names
-- Baby names sourced from Social Security Administration (SSA)
-- https://www.ssa.gov/oact/babynames/
-- Generated: 2025-01-08

-- ============================================
-- USA NAMES - Female
-- ============================================

INSERT INTO names (name, gender, country, origin, meaning, popularity_rank, registration_count) VALUES
-- Top US female names (2020-2023)
('Olivia', 'F', 'US', 'Latin', 'Olive tree, symbol of peace', 1, 17728),
('Emma', 'F', 'US', 'German', 'Whole, universal', 2, 15433),
('Charlotte', 'F', 'US', 'French', 'Free woman', 3, 13285),
('Amelia', 'F', 'US', 'German', 'Industrious, striving', 4, 12952),
('Sophia', 'F', 'US', 'Greek', 'Wisdom', 5, 12496),
('Mia', 'F', 'US', 'Scandinavian', 'Beloved, mine', 6, 11285),
('Ava', 'F', 'US', 'Latin', 'Like a bird', 7, 11272),
('Isabella', 'F', 'US', 'Hebrew', 'Devoted to God', 8, 10953),
('Luna', 'F', 'US', 'Latin', 'Moon', 9, 10285),
('Evelyn', 'F', 'US', 'English', 'Wished for child', 10, 9434),
('Harper', 'F', 'US', 'English', 'Harp player', 11, 8388),
('Camila', 'F', 'US', 'Latin', 'Young ceremonial attendant', 12, 8285),
('Gianna', 'F', 'US', 'Italian', 'God is gracious', 13, 7983),
('Abigail', 'F', 'US', 'Hebrew', 'Father''s joy', 14, 7839),
('Aria', 'F', 'US', 'Italian', 'Air, melody', 15, 7615),
('Ella', 'F', 'US', 'German', 'Fairy maiden, light', 16, 7514),
('Elizabeth', 'F', 'US', 'Hebrew', 'Pledged to God', 17, 7285),
('Sofia', 'F', 'US', 'Greek', 'Wisdom', 18, 7115),
('Emily', 'F', 'US', 'Latin', 'Rival, eager', 19, 6952),
('Avery', 'F', 'US', 'English', 'Ruler of elves', 20, 6833),
('Mila', 'F', 'US', 'Slavic', 'Gracious, dear', 21, 6715),
('Scarlett', 'F', 'US', 'English', 'Red, scarlet color', 22, 6598),
('Eleanor', 'F', 'US', 'Greek', 'Bright, shining light', 23, 6483),
('Madison', 'F', 'US', 'English', 'Son of Matthew', 24, 6372),
('Layla', 'F', 'US', 'Arabic', 'Night, dark beauty', 25, 6285),
('Penelope', 'F', 'US', 'Greek', 'Weaver', 26, 6183),
('Riley', 'F', 'US', 'Irish', 'Courageous', 27, 6072),
('Chloe', 'F', 'US', 'Greek', 'Blooming', 28, 5985),
('Zoey', 'F', 'US', 'Greek', 'Life', 29, 5915),
('Nora', 'F', 'US', 'Irish', 'Honor, light', 30, 5825),
('Lily', 'F', 'US', 'English', 'Lily flower, purity', 31, 5752),
('Hazel', 'F', 'US', 'English', 'Hazelnut tree', 32, 5683),
('Violet', 'F', 'US', 'Latin', 'Purple flower', 33, 5583),
('Aurora', 'F', 'US', 'Latin', 'Dawn', 34, 5492),
('Willow', 'F', 'US', 'English', 'Willow tree, graceful', 35, 5415),
('Stella', 'F', 'US', 'Latin', 'Star', 36, 5328),
('Zoe', 'F', 'US', 'Greek', 'Life', 37, 5285),
('Victoria', 'F', 'US', 'Latin', 'Victory', 38, 5183),
('Hannah', 'F', 'US', 'Hebrew', 'Grace, favor', 39, 5115),
('Addison', 'F', 'US', 'English', 'Son of Adam', 40, 5028),
('Leah', 'F', 'US', 'Hebrew', 'Weary, delicate', 41, 4952),
('Lucy', 'F', 'US', 'Latin', 'Light', 42, 4893),
('Eliana', 'F', 'US', 'Hebrew', 'God has answered', 43, 4815),
('Ivy', 'F', 'US', 'English', 'Ivy plant, fidelity', 44, 4752),
('Everly', 'F', 'US', 'English', 'From the boar meadow', 45, 4683),
('Emilia', 'F', 'US', 'Latin', 'Rival, eager', 46, 4615),
('Paisley', 'F', 'US', 'Scottish', 'Church, cemetery', 47, 4552),
('Naomi', 'F', 'US', 'Hebrew', 'Pleasantness', 48, 4483),
('Elena', 'F', 'US', 'Greek', 'Bright light, shining', 49, 4415),
('Savannah', 'F', 'US', 'Spanish', 'Treeless plain', 50, 4352),
('Brooklyn', 'F', 'US', 'American', 'Water, stream', 51, 4285),
('Claire', 'F', 'US', 'French', 'Clear, bright', 52, 4225),
('Audrey', 'F', 'US', 'English', 'Noble strength', 53, 4172),
('Skylar', 'F', 'US', 'Dutch', 'Scholar', 54, 4115),
('Bella', 'F', 'US', 'Italian', 'Beautiful', 55, 4052),
('Genesis', 'F', 'US', 'Greek', 'Origin, beginning', 56, 3995),
('Aaliyah', 'F', 'US', 'Arabic', 'High, exalted', 57, 3938),
('Kennedy', 'F', 'US', 'Irish', 'Helmeted chief', 58, 3883),
('Kinsley', 'F', 'US', 'English', 'King''s meadow', 59, 3825),
('Maya', 'F', 'US', 'Sanskrit', 'Illusion, magic', 60, 3772),
('Sadie', 'F', 'US', 'Hebrew', 'Princess', 61, 3718),
('Autumn', 'F', 'US', 'Latin', 'Fall season', 62, 3665),
('Piper', 'F', 'US', 'English', 'Pipe player', 63, 3615),
('Ruby', 'F', 'US', 'Latin', 'Red gemstone', 64, 3562),
('Serenity', 'F', 'US', 'Latin', 'Calm, peaceful', 65, 3512),
('Quinn', 'F', 'US', 'Irish', 'Wise, counsel', 66, 3458),
('Peyton', 'F', 'US', 'English', 'Fighting man''s estate', 67, 3408),
('Madelyn', 'F', 'US', 'English', 'High tower', 68, 3358),
('Lydia', 'F', 'US', 'Greek', 'From Lydia', 69, 3312),
('Alexa', 'F', 'US', 'Greek', 'Defender of mankind', 70, 3262),
('Aubrey', 'F', 'US', 'German', 'Elf ruler', 71, 3215),
('Katherine', 'F', 'US', 'Greek', 'Pure', 72, 3168),
('Cora', 'F', 'US', 'Greek', 'Maiden', 73, 3122),
('Madeline', 'F', 'US', 'French', 'High tower', 74, 3078),
('Nevaeh', 'F', 'US', 'American', 'Heaven spelled backwards', 75, 3035),
('Eva', 'F', 'US', 'Hebrew', 'Life', 76, 2992),
('Melody', 'F', 'US', 'Greek', 'Song, music', 77, 2952),
('Ellie', 'F', 'US', 'Greek', 'Bright light', 78, 2912),
('Sarah', 'F', 'US', 'Hebrew', 'Princess', 79, 2872),
('Josephine', 'F', 'US', 'Hebrew', 'God will increase', 80, 2835),
('Anna', 'F', 'US', 'Hebrew', 'Grace', 81, 2798),
('Athena', 'F', 'US', 'Greek', 'Goddess of wisdom', 82, 2762),
('Leilani', 'F', 'US', 'Hawaiian', 'Heavenly flower', 83, 2725),
('Caroline', 'F', 'US', 'German', 'Free woman', 84, 2692),
('Nova', 'F', 'US', 'Latin', 'New, young star', 85, 2658),
('Natalie', 'F', 'US', 'Latin', 'Christmas Day', 86, 2625),
('Valentina', 'F', 'US', 'Latin', 'Strong, healthy', 87, 2592),
('Hailey', 'F', 'US', 'English', 'Hay meadow', 88, 2562),
('Emery', 'F', 'US', 'German', 'Industrious ruler', 89, 2532),
('Alexandra', 'F', 'US', 'Greek', 'Defender of mankind', 90, 2502),
('Iris', 'F', 'US', 'Greek', 'Rainbow', 91, 2472),
('Delilah', 'F', 'US', 'Hebrew', 'Delicate, languishing', 92, 2445),
('Ariana', 'F', 'US', 'Italian', 'Most holy', 93, 2418),
('Lyla', 'F', 'US', 'Arabic', 'Night', 94, 2392),
('Allison', 'F', 'US', 'German', 'Noble', 95, 2365),
('Jade', 'F', 'US', 'Spanish', 'Green stone', 96, 2342),
('Arya', 'F', 'US', 'Sanskrit', 'Noble, honorable', 97, 2318),
('Lillian', 'F', 'US', 'Latin', 'Lily, purity', 98, 2295),
('Rose', 'F', 'US', 'Latin', 'Rose flower', 99, 2272),
('Margot', 'F', 'US', 'French', 'Pearl', 100, 2252);

-- ============================================
-- USA NAMES - Male
-- ============================================

INSERT INTO names (name, gender, country, origin, meaning, popularity_rank, registration_count) VALUES
-- Top US male names (2020-2023)
('Liam', 'M', 'US', 'Irish', 'Strong-willed warrior', 1, 20456),
('Noah', 'M', 'US', 'Hebrew', 'Rest, comfort', 2, 18739),
('Oliver', 'M', 'US', 'Latin', 'Olive tree, peace', 3, 14616),
('James', 'M', 'US', 'Hebrew', 'Supplanter', 4, 12367),
('Elijah', 'M', 'US', 'Hebrew', 'My God is Yahweh', 5, 12265),
('William', 'M', 'US', 'German', 'Resolute protector', 6, 12088),
('Henry', 'M', 'US', 'German', 'Ruler of the home', 7, 11307),
('Lucas', 'M', 'US', 'Greek', 'Light, illumination', 8, 11185),
('Benjamin', 'M', 'US', 'Hebrew', 'Son of the right hand', 9, 10983),
('Theodore', 'M', 'US', 'Greek', 'Gift of God', 10, 9535),
('Jack', 'M', 'US', 'English', 'God is gracious', 11, 9388),
('Levi', 'M', 'US', 'Hebrew', 'Joined, attached', 12, 9285),
('Alexander', 'M', 'US', 'Greek', 'Defender of the people', 13, 8952),
('Jackson', 'M', 'US', 'English', 'Son of Jack', 14, 8562),
('Mason', 'M', 'US', 'French', 'Stone worker', 15, 8352),
('Sebastian', 'M', 'US', 'Greek', 'Venerable, revered', 16, 8185),
('Ethan', 'M', 'US', 'Hebrew', 'Strong, firm', 17, 8065),
('Mateo', 'M', 'US', 'Spanish', 'Gift of God', 18, 7925),
('Daniel', 'M', 'US', 'Hebrew', 'God is my judge', 19, 7812),
('Michael', 'M', 'US', 'Hebrew', 'Who is like God?', 20, 7695),
('Owen', 'M', 'US', 'Welsh', 'Young warrior, noble', 21, 7582),
('Logan', 'M', 'US', 'Scottish', 'Little hollow', 22, 7475),
('Aiden', 'M', 'US', 'Irish', 'Little fire', 23, 7365),
('Samuel', 'M', 'US', 'Hebrew', 'God has heard', 24, 7258),
('Joseph', 'M', 'US', 'Hebrew', 'He will add', 25, 7152),
('Jacob', 'M', 'US', 'Hebrew', 'Supplanter', 26, 7048),
('Asher', 'M', 'US', 'Hebrew', 'Happy, blessed', 27, 6945),
('Luke', 'M', 'US', 'Greek', 'Light-giving', 28, 6845),
('David', 'M', 'US', 'Hebrew', 'Beloved', 29, 6748),
('Leo', 'M', 'US', 'Latin', 'Lion', 30, 6652),
('Wyatt', 'M', 'US', 'English', 'Brave in war', 31, 6558),
('Matthew', 'M', 'US', 'Hebrew', 'Gift of God', 32, 6465),
('John', 'M', 'US', 'Hebrew', 'God is gracious', 33, 6375),
('Carter', 'M', 'US', 'English', 'Cart driver', 34, 6285),
('Julian', 'M', 'US', 'Latin', 'Youthful, downy', 35, 6198),
('Grayson', 'M', 'US', 'English', 'Son of the steward', 36, 6112),
('Isaac', 'M', 'US', 'Hebrew', 'Laughter', 37, 6028),
('Jayden', 'M', 'US', 'American', 'Thankful, God will judge', 38, 5945),
('Gabriel', 'M', 'US', 'Hebrew', 'God is my strength', 39, 5865),
('Anthony', 'M', 'US', 'Latin', 'Priceless one', 40, 5785),
('Dylan', 'M', 'US', 'Welsh', 'Son of the sea', 41, 5708),
('Lincoln', 'M', 'US', 'English', 'Lake colony', 42, 5632),
('Thomas', 'M', 'US', 'Aramaic', 'Twin', 43, 5558),
('Maverick', 'M', 'US', 'American', 'Independent, nonconformist', 44, 5485),
('Ezra', 'M', 'US', 'Hebrew', 'Helper', 45, 5415),
('Christopher', 'M', 'US', 'Greek', 'Bearer of Christ', 46, 5345),
('Charles', 'M', 'US', 'German', 'Free man', 47, 5278),
('Josiah', 'M', 'US', 'Hebrew', 'God supports', 48, 5212),
('Caleb', 'M', 'US', 'Hebrew', 'Faithful, devoted', 49, 5148),
('Hudson', 'M', 'US', 'English', 'Son of Hugh', 50, 5085),
('Christian', 'M', 'US', 'Latin', 'Follower of Christ', 51, 5025),
('Landon', 'M', 'US', 'English', 'Long hill', 52, 4965),
('Adrian', 'M', 'US', 'Latin', 'From Hadria', 53, 4908),
('Isaiah', 'M', 'US', 'Hebrew', 'Salvation of the Lord', 54, 4852),
('Andrew', 'M', 'US', 'Greek', 'Manly, brave', 55, 4798),
('Joshua', 'M', 'US', 'Hebrew', 'The Lord is salvation', 56, 4745),
('Nathan', 'M', 'US', 'Hebrew', 'He gave', 57, 4692),
('Nolan', 'M', 'US', 'Irish', 'Champion', 58, 4642),
('Hunter', 'M', 'US', 'English', 'One who hunts', 59, 4592),
('Eli', 'M', 'US', 'Hebrew', 'Ascended, uplifted', 60, 4545),
('Cameron', 'M', 'US', 'Scottish', 'Crooked nose', 61, 4498),
('Connor', 'M', 'US', 'Irish', 'Lover of hounds', 62, 4452),
('Aaron', 'M', 'US', 'Hebrew', 'High mountain, exalted', 63, 4408),
('Colton', 'M', 'US', 'English', 'Coal town', 64, 4365),
('Robert', 'M', 'US', 'German', 'Bright fame', 65, 4322),
('Angel', 'M', 'US', 'Greek', 'Messenger', 66, 4282),
('Beau', 'M', 'US', 'French', 'Handsome', 67, 4242),
('Jaxon', 'M', 'US', 'American', 'Son of Jack', 68, 4202),
('Dominic', 'M', 'US', 'Latin', 'Belonging to the Lord', 69, 4165),
('Greyson', 'M', 'US', 'English', 'Son of the steward', 70, 4128),
('Ian', 'M', 'US', 'Scottish', 'God is gracious', 71, 4092),
('Austin', 'M', 'US', 'Latin', 'Great, magnificent', 72, 4058),
('Evan', 'M', 'US', 'Welsh', 'Young warrior', 73, 4025),
('Miles', 'M', 'US', 'Latin', 'Soldier', 74, 3992),
('Wesley', 'M', 'US', 'English', 'Western meadow', 75, 3960),
('Kai', 'M', 'US', 'Hawaiian', 'Sea', 76, 3928),
('Carson', 'M', 'US', 'Scottish', 'Son of Carr', 77, 3898),
('Jason', 'M', 'US', 'Greek', 'Healer', 78, 3868),
('Cooper', 'M', 'US', 'English', 'Barrel maker', 79, 3838),
('Declan', 'M', 'US', 'Irish', 'Full of goodness', 80, 3810),
('Jeremiah', 'M', 'US', 'Hebrew', 'Exalted of the Lord', 81, 3782),
('Easton', 'M', 'US', 'English', 'East town', 82, 3755),
('Parker', 'M', 'US', 'English', 'Park keeper', 83, 3728),
('Roman', 'M', 'US', 'Latin', 'Citizen of Rome', 84, 3702),
('Axel', 'M', 'US', 'Scandinavian', 'Father of peace', 85, 3678),
('Jameson', 'M', 'US', 'English', 'Son of James', 86, 3652),
('Kayden', 'M', 'US', 'American', 'Fighter', 87, 3628),
('Jose', 'M', 'US', 'Spanish', 'God will increase', 88, 3605),
('Bennett', 'M', 'US', 'Latin', 'Blessed', 89, 3582),
('Everett', 'M', 'US', 'German', 'Brave as a wild boar', 90, 3558),
('Santiago', 'M', 'US', 'Spanish', 'Saint James', 91, 3538),
('Weston', 'M', 'US', 'English', 'Western town', 92, 3515),
('Ryker', 'M', 'US', 'Danish', 'Rich', 93, 3495),
('Kevin', 'M', 'US', 'Irish', 'Handsome, gentle', 94, 3472),
('Gavin', 'M', 'US', 'Welsh', 'White hawk', 95, 3452),
('Chase', 'M', 'US', 'French', 'Hunter', 96, 3432),
('Giovanni', 'M', 'US', 'Italian', 'God is gracious', 97, 3412),
('Adam', 'M', 'US', 'Hebrew', 'Man, earth', 98, 3392),
('Jace', 'M', 'US', 'American', 'Healer', 99, 3375),
('Nicholas', 'M', 'US', 'Greek', 'Victory of the people', 100, 3355);
